// Guest-native public CoreText string constants.
//
// These values are stable API keys. Defining them directly avoids one native
// symbol lookup per constant while the guest framework is being initialized.

#import <CoreText/CoreText.h>

#define LC32_CT_STRING(name, value) \
    const CFStringRef name = CFSTR(value)

LC32_CT_STRING(kCTBackgroundColorAttributeName, "CTBackgroundColor");
LC32_CT_STRING(kCTBaselineClassAttributeName, "CTBaselineClass");
LC32_CT_STRING(kCTBaselineClassHanging, "CTBaselineClassHanging");
LC32_CT_STRING(kCTBaselineClassIdeographicCentered, "CTBaselineClassIdeographicCentered");
LC32_CT_STRING(kCTBaselineClassIdeographicHigh, "CTBaselineClassIdeographicHigh");
LC32_CT_STRING(kCTBaselineClassIdeographicLow, "CTBaselineClassIdeographicLow");
LC32_CT_STRING(kCTBaselineClassMath, "CTBaselineClassMath");
LC32_CT_STRING(kCTBaselineClassRoman, "CTBaselineClassRoman");
LC32_CT_STRING(kCTBaselineInfoAttributeName, "CTBaselineInfo");
LC32_CT_STRING(kCTBaselineOriginalFont, "CTBaselineOriginalFont");
LC32_CT_STRING(kCTBaselineReferenceFont, "CTBaselineReferenceFont");
LC32_CT_STRING(kCTBaselineReferenceInfoAttributeName, "CTBaselineReferenceInfo");
LC32_CT_STRING(kCTCharacterShapeAttributeName, "NSCharacterShape");
LC32_CT_STRING(kCTFontAttributeName, "NSFont");
LC32_CT_STRING(kCTFontBaselineAdjustAttribute, "NSCTFontBaselineAdjustAttribute");
LC32_CT_STRING(kCTFontCascadeListAttribute, "NSCTFontCascadeListAttribute");
LC32_CT_STRING(kCTFontCharacterSetAttribute, "NSCTFontCharacterSetAttribute");
LC32_CT_STRING(kCTFontCollectionDisallowAutoActivationOption, "NSCTFontCollectionDisallowAutoActivationOption");
LC32_CT_STRING(kCTFontCollectionIncludeDisabledFontsOption, "NSCTFontCollectionIncludeDisabledFontsOption");
LC32_CT_STRING(kCTFontCollectionRemoveDuplicatesOption, "NSCTFontCollectionRemoveDuplicatesOption");
LC32_CT_STRING(kCTFontCopyrightNameKey, "CTFontCopyrightName");
LC32_CT_STRING(kCTFontDescriptionNameKey, "CTFontDescriptionName");
LC32_CT_STRING(kCTFontDescriptorMatchingCurrentAssetSize, "CTFontDescriptorMatchingCurrentAssetSize");
LC32_CT_STRING(kCTFontDescriptorMatchingDescriptors, "CTFontDescriptorMatchingDescriptors");
LC32_CT_STRING(kCTFontDescriptorMatchingError, "CTFontDescriptorMatchingError");
LC32_CT_STRING(kCTFontDescriptorMatchingPercentage, "CTFontDescriptorMatchingPercentage");
LC32_CT_STRING(kCTFontDescriptorMatchingResult, "CTFontDescriptorMatchingResult");
LC32_CT_STRING(kCTFontDescriptorMatchingSourceDescriptor, "CTFontDescriptorMatchingSourceDescriptor");
LC32_CT_STRING(kCTFontDescriptorMatchingTotalAssetSize, "CTFontDescriptorMatchingTotalAssetSize");
LC32_CT_STRING(kCTFontDescriptorMatchingTotalDownloadedSize, "CTFontDescriptorMatchingTotalDownloadedSize");
LC32_CT_STRING(kCTFontDesignerNameKey, "CTFontDesignerName");
LC32_CT_STRING(kCTFontDesignerURLNameKey, "CTFontDesignerURLName");
LC32_CT_STRING(kCTFontDisplayNameAttribute, "NSFontVisibleNameAttribute");
LC32_CT_STRING(kCTFontDownloadableAttribute, "NSCTFontDownloadableAttribute");
LC32_CT_STRING(kCTFontDownloadedAttribute, "NSCTFontDownloadedAttribute");
LC32_CT_STRING(kCTFontEnabledAttribute, "NSCTFontEnabledAttribute");
LC32_CT_STRING(kCTFontFamilyNameAttribute, "NSFontFamilyAttribute");
LC32_CT_STRING(kCTFontFamilyNameKey, "CTFontFamilyName");
LC32_CT_STRING(kCTFontFeatureSelectorDefaultKey, "CTFeatureSelectorDefault");
LC32_CT_STRING(kCTFontFeatureSelectorIdentifierKey, "CTFeatureSelectorIdentifier");
LC32_CT_STRING(kCTFontFeatureSelectorNameKey, "CTFeatureSelectorName");
LC32_CT_STRING(kCTFontFeatureSelectorSettingKey, "CTFeatureSelectorSetting");
LC32_CT_STRING(kCTFontFeatureSettingsAttribute, "NSCTFontFeatureSettingsAttribute");
LC32_CT_STRING(kCTFontFeatureTypeExclusiveKey, "CTFeatureTypeExclusive");
LC32_CT_STRING(kCTFontFeatureTypeIdentifierKey, "CTFeatureTypeIdentifier");
LC32_CT_STRING(kCTFontFeatureTypeNameKey, "CTFeatureTypeName");
LC32_CT_STRING(kCTFontFeatureTypeSelectorsKey, "CTFeatureTypeSelectors");
LC32_CT_STRING(kCTFontFeaturesAttribute, "NSCTFontFeaturesAttribute");
LC32_CT_STRING(kCTFontFixedAdvanceAttribute, "NSCTFontFixedAdvanceAttribute");
LC32_CT_STRING(kCTFontFormatAttribute, "NSCTFontFormatAttribute");
LC32_CT_STRING(kCTFontFullNameKey, "CTFontFullName");
LC32_CT_STRING(kCTFontLanguagesAttribute, "NSCTFontLanguagesAttribute");
LC32_CT_STRING(kCTFontLicenseNameKey, "CTFontLicenseNameName");
LC32_CT_STRING(kCTFontLicenseURLNameKey, "CTFontLicenseURLName");
LC32_CT_STRING(kCTFontMacintoshEncodingsAttribute, "NSCTFontMacintoshEncodingsAttribute");
LC32_CT_STRING(kCTFontManagerBundleIdentifier, "com.apple.CoreText");
LC32_CT_STRING(kCTFontManagerErrorDomain, "com.apple.CoreText.CTFontManagerErrorDomain");
LC32_CT_STRING(kCTFontManagerErrorFontURLsKey, "CTFontManagerErrorFontURLs");
LC32_CT_STRING(kCTFontManagerRegisteredFontsChangedNotification, "CTFontManagerFontChangedNotification");
LC32_CT_STRING(kCTFontManufacturerNameKey, "CTFontManufacturerName");
LC32_CT_STRING(kCTFontMatrixAttribute, "NSCTFontMatrixAttribute");
LC32_CT_STRING(kCTFontNameAttribute, "NSFontNameAttribute");
LC32_CT_STRING(kCTFontOpenTypeFeatureTag, "CTFeatureOpenTypeTag");
LC32_CT_STRING(kCTFontOpenTypeFeatureValue, "CTFeatureOpenTypeValue");
LC32_CT_STRING(kCTFontOrientationAttribute, "NSCTFontOrientationAttribute");
LC32_CT_STRING(kCTFontPostScriptCIDNameKey, "CTFontPostScriptCIDName");
LC32_CT_STRING(kCTFontPostScriptNameKey, "CTFontPostScriptName");
LC32_CT_STRING(kCTFontPriorityAttribute, "NSCTFontPriorityAttribute");
LC32_CT_STRING(kCTFontRegistrationScopeAttribute, "NSCTFontRegistrationScopeAttribute");
LC32_CT_STRING(kCTFontSampleTextNameKey, "CTFontSampleTextName");
LC32_CT_STRING(kCTFontSizeAttribute, "NSFontSizeAttribute");
LC32_CT_STRING(kCTFontSlantTrait, "NSCTFontSlantTrait");
LC32_CT_STRING(kCTFontStyleNameAttribute, "NSFontFaceAttribute");
LC32_CT_STRING(kCTFontStyleNameKey, "CTFontSubFamilyName");
LC32_CT_STRING(kCTFontSubFamilyNameKey, "CTFontSubFamilyName");
LC32_CT_STRING(kCTFontSymbolicTrait, "NSCTFontSymbolicTrait");
LC32_CT_STRING(kCTFontTrademarkNameKey, "CTFontTrademarkName");
LC32_CT_STRING(kCTFontTraitsAttribute, "NSCTFontTraitsAttribute");
LC32_CT_STRING(kCTFontURLAttribute, "NSCTFontFileURLAttribute");
LC32_CT_STRING(kCTFontUniqueNameKey, "CTFontUniqueName");
LC32_CT_STRING(kCTFontVariationAttribute, "NSCTFontVariationAttribute");
LC32_CT_STRING(kCTFontVariationAxisDefaultValueKey, "NSCTVariationAxisDefaultValue");
LC32_CT_STRING(kCTFontVariationAxisIdentifierKey, "NSCTVariationAxisIdentifier");
LC32_CT_STRING(kCTFontVariationAxisMaximumValueKey, "NSCTVariationAxisMaximumValue");
LC32_CT_STRING(kCTFontVariationAxisMinimumValueKey, "NSCTVariationAxisMinimumValue");
LC32_CT_STRING(kCTFontVariationAxisNameKey, "NSCTVariationAxisName");
LC32_CT_STRING(kCTFontVendorURLNameKey, "CTFontVendorURLName");
LC32_CT_STRING(kCTFontVersionNameKey, "CTFontVersionName");
LC32_CT_STRING(kCTFontWeightTrait, "NSCTFontWeightTrait");
LC32_CT_STRING(kCTFontWidthTrait, "NSCTFontProportionTrait");
LC32_CT_STRING(kCTForegroundColorAttributeName, "CTForegroundColor");
LC32_CT_STRING(kCTForegroundColorFromContextAttributeName, "CTForegroundColorFromContext");
LC32_CT_STRING(kCTFrameClippingPathsAttributeName, "CTFrameClippingPaths");
LC32_CT_STRING(kCTFramePathClippingPathAttributeName, "CTFramePathClippingPath");
LC32_CT_STRING(kCTFramePathFillRuleAttributeName, "CTFramePathFillRule");
LC32_CT_STRING(kCTFramePathWidthAttributeName, "CTFramePathWidth");
LC32_CT_STRING(kCTFrameProgressionAttributeName, "CTFrameProgression");
LC32_CT_STRING(kCTGlyphInfoAttributeName, "NSGlyphInfo");
LC32_CT_STRING(kCTHorizontalInVerticalFormsAttributeName, "CTHorizontalInVerticalForms");
LC32_CT_STRING(kCTKernAttributeName, "NSKern");
LC32_CT_STRING(kCTLanguageAttributeName, "NSLanguage");
LC32_CT_STRING(kCTLigatureAttributeName, "NSLigature");
LC32_CT_STRING(kCTParagraphStyleAttributeName, "NSParagraphStyle");
LC32_CT_STRING(kCTRubyAnnotationAttributeName, "CTRubyAnnotation");
LC32_CT_STRING(kCTRubyAnnotationScaleToFitAttributeName, "CTRubyAnnotationScaleToFit");
LC32_CT_STRING(kCTRubyAnnotationSizeFactorAttributeName, "CTRubyAnnotationSizeFactor");
LC32_CT_STRING(kCTRunDelegateAttributeName, "CTRunDelegate");
LC32_CT_STRING(kCTStrokeColorAttributeName, "CTStrokeColor");
LC32_CT_STRING(kCTStrokeWidthAttributeName, "NSStrokeWidth");
LC32_CT_STRING(kCTSuperscriptAttributeName, "CTSuperscript");
LC32_CT_STRING(kCTTabColumnTerminatorsAttributeName, "NSTabColumnTerminatorsAttributeName");
LC32_CT_STRING(kCTTypesetterOptionDisableBidiProcessing, "CTTypesetterOptionDisableBidiProcessing");
LC32_CT_STRING(kCTTypesetterOptionForcedEmbeddingLevel, "CTTypesetterOptionForcedEmbeddingLevel");
LC32_CT_STRING(kCTUnderlineColorAttributeName, "CTUnderlineColor");
LC32_CT_STRING(kCTUnderlineStyleAttributeName, "NSUnderline");
LC32_CT_STRING(kCTVerticalFormsAttributeName, "CTVerticalForms");
LC32_CT_STRING(kCTWritingDirectionAttributeName, "NSWritingDirection");

#undef LC32_CT_STRING
