// Guest-native public CoreMedia string constants.
//
// CoreMedia uses these immutable values as attachment, format-description,
// metadata, and time dictionary keys. Keeping them in the guest avoids a host
// framework dependency and preserves ordinary CFString pointer semantics.

#import <CoreMedia/CoreMedia.h>

// The iOS 10 headers macro-alias several CoreMedia exports to CoreVideo.
// Undefine those source conveniences so this compatibility image also emits
// the historical kCM symbols referenced by already-linked applications.
#undef kCMFormatDescriptionChromaLocation_Bottom
#undef kCMFormatDescriptionChromaLocation_BottomLeft
#undef kCMFormatDescriptionChromaLocation_Center
#undef kCMFormatDescriptionChromaLocation_DV420
#undef kCMFormatDescriptionChromaLocation_Left
#undef kCMFormatDescriptionChromaLocation_Top
#undef kCMFormatDescriptionChromaLocation_TopLeft
#undef kCMFormatDescriptionColorPrimaries_EBU_3213
#undef kCMFormatDescriptionColorPrimaries_ITU_R_709_2
#undef kCMFormatDescriptionColorPrimaries_SMPTE_C
#undef kCMFormatDescriptionExtension_ChromaLocationBottomField
#undef kCMFormatDescriptionExtension_ChromaLocationTopField
#undef kCMFormatDescriptionExtension_CleanAperture
#undef kCMFormatDescriptionExtension_ColorPrimaries
#undef kCMFormatDescriptionExtension_FieldCount
#undef kCMFormatDescriptionExtension_FieldDetail
#undef kCMFormatDescriptionExtension_GammaLevel
#undef kCMFormatDescriptionExtension_PixelAspectRatio
#undef kCMFormatDescriptionExtension_TransferFunction
#undef kCMFormatDescriptionExtension_VerbatimImageDescription
#undef kCMFormatDescriptionExtension_YCbCrMatrix
#undef kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly
#undef kCMFormatDescriptionFieldDetail_SpatialFirstLineLate
#undef kCMFormatDescriptionFieldDetail_TemporalBottomFirst
#undef kCMFormatDescriptionFieldDetail_TemporalTopFirst
#undef kCMFormatDescriptionKey_CleanApertureHeight
#undef kCMFormatDescriptionKey_CleanApertureHorizontalOffset
#undef kCMFormatDescriptionKey_CleanApertureVerticalOffset
#undef kCMFormatDescriptionKey_CleanApertureWidth
#undef kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing
#undef kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing
#undef kCMFormatDescriptionTransferFunction_ITU_R_709_2
#undef kCMFormatDescriptionTransferFunction_SMPTE_240M_1995
#undef kCMFormatDescriptionTransferFunction_UseGamma
#undef kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4
#undef kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2
#undef kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995


#define LC32_CM_STRING(name, value) \
    const CFStringRef name = CFSTR(value)

LC32_CM_STRING(kCMFormatDescriptionChromaLocation_Bottom, "Bottom");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_BottomLeft, "BottomLeft");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_Center, "Center");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_DV420, "DV 4:2:0");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_Left, "Left");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_Top, "Top");
LC32_CM_STRING(kCMFormatDescriptionChromaLocation_TopLeft, "TopLeft");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_DCI_P3, "DCI_P3");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_EBU_3213, "EBU_3213");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_ITU_R_2020, "ITU_R_2020");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_ITU_R_709_2, "ITU_R_709_2");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_P22, "P22");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_P3_D65, "P3_D65");
LC32_CM_STRING(kCMFormatDescriptionColorPrimaries_SMPTE_C, "SMPTE_C");
LC32_CM_STRING(kCMFormatDescriptionConformsToMPEG2VideoProfile, "ConformsToMPEG2VideoProfile");
LC32_CM_STRING(kCMFormatDescriptionExtensionKey_MetadataKeyTable, "MetadataKeyTable");
LC32_CM_STRING(kCMFormatDescriptionExtension_BytesPerRow, "CVBytesPerRow");
LC32_CM_STRING(kCMFormatDescriptionExtension_ChromaLocationBottomField, "CVImageBufferChromaLocationBottomField");
LC32_CM_STRING(kCMFormatDescriptionExtension_ChromaLocationTopField, "CVImageBufferChromaLocationTopField");
LC32_CM_STRING(kCMFormatDescriptionExtension_CleanAperture, "CVCleanAperture");
LC32_CM_STRING(kCMFormatDescriptionExtension_ColorPrimaries, "CVImageBufferColorPrimaries");
LC32_CM_STRING(kCMFormatDescriptionExtension_Depth, "Depth");
LC32_CM_STRING(kCMFormatDescriptionExtension_FieldCount, "CVFieldCount");
LC32_CM_STRING(kCMFormatDescriptionExtension_FieldDetail, "CVFieldDetail");
LC32_CM_STRING(kCMFormatDescriptionExtension_FormatName, "FormatName");
LC32_CM_STRING(kCMFormatDescriptionExtension_FullRangeVideo, "FullRangeVideo");
LC32_CM_STRING(kCMFormatDescriptionExtension_GammaLevel, "CVImageBufferGammaLevel");
LC32_CM_STRING(kCMFormatDescriptionExtension_ICCProfile, "CVImageBufferICCProfile");
LC32_CM_STRING(kCMFormatDescriptionExtension_OriginalCompressionSettings, "com.apple.fig.format_description.original_compression_settings");
LC32_CM_STRING(kCMFormatDescriptionExtension_PixelAspectRatio, "CVPixelAspectRatio");
LC32_CM_STRING(kCMFormatDescriptionExtension_RevisionLevel, "RevisionLevel");
LC32_CM_STRING(kCMFormatDescriptionExtension_SampleDescriptionExtensionAtoms, "SampleDescriptionExtensionAtoms");
LC32_CM_STRING(kCMFormatDescriptionExtension_SpatialQuality, "SpatialQuality");
LC32_CM_STRING(kCMFormatDescriptionExtension_TemporalQuality, "TemporalQuality");
LC32_CM_STRING(kCMFormatDescriptionExtension_TransferFunction, "CVImageBufferTransferFunction");
LC32_CM_STRING(kCMFormatDescriptionExtension_Vendor, "Vendor");
LC32_CM_STRING(kCMFormatDescriptionExtension_VerbatimISOSampleEntry, "VerbatimISOSampleEntry");
LC32_CM_STRING(kCMFormatDescriptionExtension_VerbatimImageDescription, "VerbatimSampleDescription");
LC32_CM_STRING(kCMFormatDescriptionExtension_VerbatimSampleDescription, "VerbatimSampleDescription");
LC32_CM_STRING(kCMFormatDescriptionExtension_Version, "Version");
LC32_CM_STRING(kCMFormatDescriptionExtension_YCbCrMatrix, "CVImageBufferYCbCrMatrix");
LC32_CM_STRING(kCMFormatDescriptionFieldDetail_SpatialFirstLineEarly, "SpatialFirstLineEarly");
LC32_CM_STRING(kCMFormatDescriptionFieldDetail_SpatialFirstLineLate, "SpatialFirstLineLate");
LC32_CM_STRING(kCMFormatDescriptionFieldDetail_TemporalBottomFirst, "TemporalBottomFirst");
LC32_CM_STRING(kCMFormatDescriptionFieldDetail_TemporalTopFirst, "TemporalTopFirst");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureHeight, "Height");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureHeightRational, "HeightAsRational");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureHorizontalOffset, "HorizontalOffset");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureHorizontalOffsetRational, "HorizontalOffsetAsRational");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureVerticalOffset, "VerticalOffset");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureVerticalOffsetRational, "VerticalOffsetAsRational");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureWidth, "Width");
LC32_CM_STRING(kCMFormatDescriptionKey_CleanApertureWidthRational, "WidthAsRational");
LC32_CM_STRING(kCMFormatDescriptionKey_PixelAspectRatioHorizontalSpacing, "HorizontalSpacing");
LC32_CM_STRING(kCMFormatDescriptionKey_PixelAspectRatioVerticalSpacing, "VerticalSpacing");
LC32_CM_STRING(kCMFormatDescriptionTransferFunction_ITU_R_2020, "ITU_R_2020");
LC32_CM_STRING(kCMFormatDescriptionTransferFunction_ITU_R_709_2, "ITU_R_709_2");
LC32_CM_STRING(kCMFormatDescriptionTransferFunction_SMPTE_240M_1995, "SMPTE_240M_1995");
LC32_CM_STRING(kCMFormatDescriptionTransferFunction_SMPTE_ST_428_1, "SMPTE_ST_428_1");
LC32_CM_STRING(kCMFormatDescriptionTransferFunction_UseGamma, "UseGamma");
LC32_CM_STRING(kCMFormatDescriptionVendor_Apple, "appl");
LC32_CM_STRING(kCMFormatDescriptionYCbCrMatrix_ITU_R_2020, "ITU_R_2020");
LC32_CM_STRING(kCMFormatDescriptionYCbCrMatrix_ITU_R_601_4, "ITU_R_601_4");
LC32_CM_STRING(kCMFormatDescriptionYCbCrMatrix_ITU_R_709_2, "ITU_R_709_2");
LC32_CM_STRING(kCMFormatDescriptionYCbCrMatrix_SMPTE_240M_1995, "SMPTE_240M_1995");
LC32_CM_STRING(kCMImageDescriptionFlavor_3GPFamily, "3GPFamily");
LC32_CM_STRING(kCMImageDescriptionFlavor_ISOFamily, "ISOFamily");
LC32_CM_STRING(kCMImageDescriptionFlavor_QuickTimeMovie, "QuickTimeMovie");
LC32_CM_STRING(kCMMetadataBaseDataType_AffineTransformF64, "com.apple.metadata.affine-transform-float64");
LC32_CM_STRING(kCMMetadataBaseDataType_BMP, "com.apple.metadata.datatype.BMP");
LC32_CM_STRING(kCMMetadataBaseDataType_DimensionsF32, "com.apple.metadata.datatype.dimensions-float32");
LC32_CM_STRING(kCMMetadataBaseDataType_Float32, "com.apple.metadata.datatype.float32");
LC32_CM_STRING(kCMMetadataBaseDataType_Float64, "com.apple.metadata.datatype.float64");
LC32_CM_STRING(kCMMetadataBaseDataType_GIF, "com.apple.metadata.datatype.GIF");
LC32_CM_STRING(kCMMetadataBaseDataType_JPEG, "com.apple.metadata.datatype.JPEG");
LC32_CM_STRING(kCMMetadataBaseDataType_JSON, "com.apple.metadata.datatype.JSON");
LC32_CM_STRING(kCMMetadataBaseDataType_PNG, "com.apple.metadata.datatype.PNG");
LC32_CM_STRING(kCMMetadataBaseDataType_PointF32, "com.apple.metadata.datatype.point-float32");
LC32_CM_STRING(kCMMetadataBaseDataType_PolygonF32, "com.apple.metadata.datatype.polygon-float32");
LC32_CM_STRING(kCMMetadataBaseDataType_PolylineF32, "com.apple.metadata.datatype.polyline-float32");
LC32_CM_STRING(kCMMetadataBaseDataType_RawData, "com.apple.metadata.datatype.raw-data");
LC32_CM_STRING(kCMMetadataBaseDataType_RectF32, "com.apple.metadata.datatype.rectangle-float32");
LC32_CM_STRING(kCMMetadataBaseDataType_SInt16, "com.apple.metadata.datatype.int16");
LC32_CM_STRING(kCMMetadataBaseDataType_SInt32, "com.apple.metadata.datatype.int32");
LC32_CM_STRING(kCMMetadataBaseDataType_SInt64, "com.apple.metadata.datatype.int64");
LC32_CM_STRING(kCMMetadataBaseDataType_SInt8, "com.apple.metadata.datatype.int8");
LC32_CM_STRING(kCMMetadataBaseDataType_UInt16, "com.apple.metadata.datatype.uint16");
LC32_CM_STRING(kCMMetadataBaseDataType_UInt32, "com.apple.metadata.datatype.uint32");
LC32_CM_STRING(kCMMetadataBaseDataType_UInt64, "com.apple.metadata.datatype.uint64");
LC32_CM_STRING(kCMMetadataBaseDataType_UInt8, "com.apple.metadata.datatype.uint8");
LC32_CM_STRING(kCMMetadataBaseDataType_UTF16, "com.apple.metadata.datatype.UTF-16");
LC32_CM_STRING(kCMMetadataBaseDataType_UTF8, "com.apple.metadata.datatype.UTF-8");
LC32_CM_STRING(kCMMetadataDataType_QuickTimeMetadataDirection, "com.apple.quicktime.direction");
LC32_CM_STRING(kCMMetadataDataType_QuickTimeMetadataLocation_ISO6709, "com.apple.quicktime.location.ISO6709");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_ConformingDataTypes, "MetadataKeyConformingDataTypes");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_DataType, "MetadataKeyDataType");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_DataTypeNamespace, "MetadataKeyDataTypeNameSpace");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_LanguageTag, "MetadataKeyLanguageTag");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_LocalID, "MetadataKeyLocalID");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_Namespace, "MetadataKeyNamespace");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_SetupData, "MetadataKeySetupData");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_StructuralDependency, "MetadataKeyStructuralDependency");
LC32_CM_STRING(kCMMetadataFormatDescriptionKey_Value, "MetadataKeyValue");
LC32_CM_STRING(kCMMetadataFormatDescriptionMetadataSpecificationKey_DataType, "MetadataDataType");
LC32_CM_STRING(kCMMetadataFormatDescriptionMetadataSpecificationKey_ExtendedLanguageTag, "MetadataExtendedLanguageTag");
LC32_CM_STRING(kCMMetadataFormatDescriptionMetadataSpecificationKey_Identifier, "MetadataIdentifier");
LC32_CM_STRING(kCMMetadataFormatDescriptionMetadataSpecificationKey_SetupData, "MetadataKeySetupData");
LC32_CM_STRING(kCMMetadataFormatDescriptionMetadataSpecificationKey_StructuralDependency, "StructuralDependency");
LC32_CM_STRING(kCMMetadataFormatDescription_StructuralDependencyKey_DependencyIsInvalidFlag, "StructuralDependencyIsInvalidFlag");
LC32_CM_STRING(kCMMetadataIdentifier_QuickTimeMetadataDirection_Facing, "mdta/com.apple.quicktime.direction.facing");
LC32_CM_STRING(kCMMetadataIdentifier_QuickTimeMetadataLocation_ISO6709, "mdta/com.apple.quicktime.location.ISO6709");
LC32_CM_STRING(kCMMetadataIdentifier_QuickTimeMetadataPreferredAffineTransform, "mdta/com.apple.quicktime.preferred-affine-transform");
LC32_CM_STRING(kCMMetadataIdentifier_QuickTimeMetadataVideoOrientation, "mdta/com.apple.quicktime.video-orientation");
LC32_CM_STRING(kCMMetadataKeySpace_HLSDateRange, "lsdr");
LC32_CM_STRING(kCMMetadataKeySpace_ID3, "org.id3");
LC32_CM_STRING(kCMMetadataKeySpace_ISOUserData, "uiso");
LC32_CM_STRING(kCMMetadataKeySpace_Icy, "icy");
LC32_CM_STRING(kCMMetadataKeySpace_QuickTimeMetadata, "mdta");
LC32_CM_STRING(kCMMetadataKeySpace_QuickTimeUserData, "udta");
LC32_CM_STRING(kCMMetadataKeySpace_iTunes, "itsk");
LC32_CM_STRING(kCMSampleAttachmentKey_DependsOnOthers, "DependsOnOthers");
LC32_CM_STRING(kCMSampleAttachmentKey_DisplayImmediately, "DisplayImmediately");
LC32_CM_STRING(kCMSampleAttachmentKey_DoNotDisplay, "DoNotDisplay");
LC32_CM_STRING(kCMSampleAttachmentKey_EarlierDisplayTimesAllowed, "EarlierDisplayTimesAllowed");
LC32_CM_STRING(kCMSampleAttachmentKey_HasRedundantCoding, "HasRedundantCoding");
LC32_CM_STRING(kCMSampleAttachmentKey_IsDependedOnByOthers, "IsDependedOnByOthers");
LC32_CM_STRING(kCMSampleAttachmentKey_NotSync, "NotSync");
LC32_CM_STRING(kCMSampleAttachmentKey_PartialSync, "PartialSync");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_DisplayEmptyMediaImmediately, "DisplayEmptyMediaImmediately");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_DrainAfterDecoding, "DrainAfterDecoding");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_DroppedFrameReason, "DroppedFrameReason");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_DroppedFrameReasonInfo, "DroppedFrameReasonInfo");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_EmptyMedia, "EmptyMedia");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_EndsPreviousSampleDuration, "EndsPreviousSampleDuration");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_FillDiscontinuitiesWithSilence, "FillDiscontinuitiesWithSilence");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_ForceKeyFrame, "ForceKeyFrame");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_GradualDecoderRefresh, "GradualDecoderRefresh");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_PermanentEmptyMedia, "PermanentEmptyMedia");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_PostNotificationWhenConsumed, "PostNotificationWhenConsumed");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_ResetDecoderBeforeDecoding, "ResetDecoderBeforeDecoding");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_ResumeOutput, "ResumeOutput");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_Reverse, "Reverse");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_SampleReferenceByteOffset, "SampleReferenceByteOffset");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_SampleReferenceURL, "SampleReferenceURL");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_SpeedMultiplier, "SpeedMultiplier");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_StillImageLensStabilizationInfo, "StillImageLensStabilizationInfo");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_TransitionID, "TransitionID");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_TrimDurationAtEnd, "TrimDurationAtEnd");
LC32_CM_STRING(kCMSampleBufferAttachmentKey_TrimDurationAtStart, "TrimDurationAtStart");
LC32_CM_STRING(kCMSampleBufferConduitNotificationParameter_MaxUpcomingOutputPTS, "MaxUpcomingOutputPTS");
LC32_CM_STRING(kCMSampleBufferConduitNotificationParameter_MinUpcomingOutputPTS, "MinUpcomingOutputPTS");
LC32_CM_STRING(kCMSampleBufferConduitNotificationParameter_ResumeTag, "ResumeTag");
LC32_CM_STRING(kCMSampleBufferConduitNotificationParameter_UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange, "UpcomingOutputPTSRangeMayOverlapQueuedOutputPTSRange");
LC32_CM_STRING(kCMSampleBufferConduitNotification_InhibitOutputUntil, "InhibitOutputUntil");
LC32_CM_STRING(kCMSampleBufferConduitNotification_ResetOutput, "ResetOutput");
LC32_CM_STRING(kCMSampleBufferConduitNotification_UpcomingOutputPTSRangeChanged, "UpcomingOutputPTSRangeChanged");
LC32_CM_STRING(kCMSampleBufferConsumerNotification_BufferConsumed, "BufferConsumed");
LC32_CM_STRING(kCMSampleBufferDroppedFrameReasonInfo_CameraModeSwitch, "CameraModeSwitch");
LC32_CM_STRING(kCMSampleBufferDroppedFrameReason_Discontinuity, "Discontinuity");
LC32_CM_STRING(kCMSampleBufferDroppedFrameReason_FrameWasLate, "FrameWasLate");
LC32_CM_STRING(kCMSampleBufferDroppedFrameReason_OutOfBuffers, "OutOfBuffers");
LC32_CM_STRING(kCMSampleBufferLensStabilizationInfo_Active, "Active");
LC32_CM_STRING(kCMSampleBufferLensStabilizationInfo_Off, "Off");
LC32_CM_STRING(kCMSampleBufferLensStabilizationInfo_OutOfRange, "OutOfRange");
LC32_CM_STRING(kCMSampleBufferLensStabilizationInfo_Unavailable, "Unavailable");
LC32_CM_STRING(kCMSampleBufferNotificationParameter_OSStatus, "OSStatus");
LC32_CM_STRING(kCMSampleBufferNotification_DataBecameReady, "FigSampleBufferDataBecameReady");
LC32_CM_STRING(kCMSampleBufferNotification_DataFailed, "CMSampleBufferDataFailed");
LC32_CM_STRING(kCMSoundDescriptionFlavor_3GPFamily, "3GPFamily");
LC32_CM_STRING(kCMSoundDescriptionFlavor_ISOFamily, "ISOFamily");
LC32_CM_STRING(kCMSoundDescriptionFlavor_QuickTimeMovie, "QuickTimeMovie");
LC32_CM_STRING(kCMSoundDescriptionFlavor_QuickTimeMovieV2, "QuickTimeMovieV2");
LC32_CM_STRING(kCMTextFormatDescriptionColor_Alpha, "Alpha");
LC32_CM_STRING(kCMTextFormatDescriptionColor_Blue, "Blue");
LC32_CM_STRING(kCMTextFormatDescriptionColor_Green, "Green");
LC32_CM_STRING(kCMTextFormatDescriptionColor_Red, "Red");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_BackgroundColor, "BackgroundColor");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_DefaultFontName, "DefaultFontName");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_DefaultStyle, "DefaultStyle");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_DefaultTextBox, "DefaultTextBox");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_DisplayFlags, "DisplayFlags");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_FontTable, "FontTable");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_HorizontalJustification, "HorizontalJustification");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_TextJustification, "TextJustification");
LC32_CM_STRING(kCMTextFormatDescriptionExtension_VerticalJustification, "VerticalJustification");
LC32_CM_STRING(kCMTextFormatDescriptionRect_Bottom, "Bottom");
LC32_CM_STRING(kCMTextFormatDescriptionRect_Left, "Left");
LC32_CM_STRING(kCMTextFormatDescriptionRect_Right, "Right");
LC32_CM_STRING(kCMTextFormatDescriptionRect_Top, "Top");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_Ascent, "Ascent");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_EndChar, "EndChar");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_Font, "Font");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_FontFace, "FontFace");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_FontSize, "FontSize");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_ForegroundColor, "ForegroundColor");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_Height, "Height");
LC32_CM_STRING(kCMTextFormatDescriptionStyle_StartChar, "StartChar");
LC32_CM_STRING(kCMTextMarkupAlignmentType_End, "CMWDA_end");
LC32_CM_STRING(kCMTextMarkupAlignmentType_Left, "CMWDA_left");
LC32_CM_STRING(kCMTextMarkupAlignmentType_Middle, "CMWDA_middle");
LC32_CM_STRING(kCMTextMarkupAlignmentType_Right, "CMWDA_right");
LC32_CM_STRING(kCMTextMarkupAlignmentType_Start, "CMWDA_start");
LC32_CM_STRING(kCMTextMarkupAttribute_Alignment, "CMWritingDirectionAlignment");
LC32_CM_STRING(kCMTextMarkupAttribute_BackgroundColorARGB, "CMBackgroundColorARGB");
LC32_CM_STRING(kCMTextMarkupAttribute_BaseFontSizePercentageRelativeToVideoHeight, "CMBaseFontSizePercentage");
LC32_CM_STRING(kCMTextMarkupAttribute_BoldStyle, "CMBoldStyle");
LC32_CM_STRING(kCMTextMarkupAttribute_CharacterBackgroundColorARGB, "CMCharacterBackgroundColorARGB");
LC32_CM_STRING(kCMTextMarkupAttribute_CharacterEdgeStyle, "CMCharacterEdgeStyle");
LC32_CM_STRING(kCMTextMarkupAttribute_FontFamilyName, "CMFontFamilyName");
LC32_CM_STRING(kCMTextMarkupAttribute_ForegroundColorARGB, "CMForegroundColorARGB");
LC32_CM_STRING(kCMTextMarkupAttribute_GenericFontFamilyName, "CMGenericFontFamilyName");
LC32_CM_STRING(kCMTextMarkupAttribute_ItalicStyle, "CMItalicStyle");
LC32_CM_STRING(kCMTextMarkupAttribute_OrthogonalLinePositionPercentageRelativeToWritingDirection, "CMWritingDirectionOrthogonalLinePositionPercentage");
LC32_CM_STRING(kCMTextMarkupAttribute_RelativeFontSize, "CMRelativeFontSize");
LC32_CM_STRING(kCMTextMarkupAttribute_TextPositionPercentageRelativeToWritingDirection, "CMWritingDirectionTextPositionPercentage");
LC32_CM_STRING(kCMTextMarkupAttribute_UnderlineStyle, "CMUnderlineStyle");
LC32_CM_STRING(kCMTextMarkupAttribute_VerticalLayout, "CMVerticalLayout");
LC32_CM_STRING(kCMTextMarkupAttribute_WritingDirectionSizePercentage, "CMWritingDirectionSizePercentage");
LC32_CM_STRING(kCMTextMarkupCharacterEdgeStyle_Depressed, "CMCharacterEdgeStyle_Depressed");
LC32_CM_STRING(kCMTextMarkupCharacterEdgeStyle_DropShadow, "CMCharacterEdgeStyle_DropShadow");
LC32_CM_STRING(kCMTextMarkupCharacterEdgeStyle_None, "CMCharacterEdgeStyle_None");
LC32_CM_STRING(kCMTextMarkupCharacterEdgeStyle_Raised, "CMCharacterEdgeStyle_Raised");
LC32_CM_STRING(kCMTextMarkupCharacterEdgeStyle_Uniform, "CMCharacterEdgeStyle_Uniform");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Casual, "CMGenericFontName_Casual");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Cursive, "CMGenericFontName_Cursive");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Default, "CMGenericFontName_Default");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Fantasy, "CMGenericFontName_Fantasy");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Monospace, "CMGenericFontName_Monospace");
LC32_CM_STRING(kCMTextMarkupGenericFontName_MonospaceSansSerif, "CMGenericFontName_MonospaceSansSerif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_MonospaceSerif, "CMGenericFontName_MonospaceSerif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_ProportionalSansSerif, "CMGenericFontName_ProportionalSansSerif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_ProportionalSerif, "CMGenericFontName_ProportionalSerif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_SansSerif, "CMGenericFontName_SansSerif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_Serif, "CMGenericFontName_Serif");
LC32_CM_STRING(kCMTextMarkupGenericFontName_SmallCapital, "CMGenericFontName_SmallCapital");
LC32_CM_STRING(kCMTextVerticalLayout_LeftToRight, "CMVerticalLayout_LeftToRight");
LC32_CM_STRING(kCMTextVerticalLayout_RightToLeft, "CMVerticalLayout_RightToLeft");
LC32_CM_STRING(kCMTimeCodeFormatDescriptionExtension_SourceReferenceName, "TimeCode_SourceReferenceName");
LC32_CM_STRING(kCMTimeCodeFormatDescriptionKey_LangCode, "TimeCode_SourceReferenceName_LangCode");
LC32_CM_STRING(kCMTimeCodeFormatDescriptionKey_Value, "TimeCode_SourceReferenceName_Value");
LC32_CM_STRING(kCMTimeEpochKey, "epoch");
LC32_CM_STRING(kCMTimeFlagsKey, "flags");
LC32_CM_STRING(kCMTimeMappingSourceKey, "source");
LC32_CM_STRING(kCMTimeMappingTargetKey, "target");
LC32_CM_STRING(kCMTimeRangeDurationKey, "duration");
LC32_CM_STRING(kCMTimeRangeStartKey, "start");
LC32_CM_STRING(kCMTimeScaleKey, "timescale");
LC32_CM_STRING(kCMTimeValueKey, "value");
LC32_CM_STRING(kCMTimebaseNotificationKey_EventTime, "CMTimebaseEventTime");
LC32_CM_STRING(kCMTimebaseNotification_EffectiveRateChanged, "CMTimebaseEffectiveRateChanged");
LC32_CM_STRING(kCMTimebaseNotification_TimeJumped, "CMTimebaseTimeJumped");

#undef LC32_CM_STRING
